name: build Blog for github pages
on:
  push:
    branches:
    - master
jobs:
  publish_blog:
    name: publish blog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
#     - name: setup node
#       uses: actions/setup-node@v3.6.0
#       with:
#         node-version: 16.x
    - name: build blog
      shell: bash
      run: |
        npm i
        npm run build
    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        name: gh-pages
        path: .vuepress/dist
      
    
      

