name: build Blog for github pages
on:
  push:
    branches:
    - master
jobs:
  publish_blog:
    name: publish blog
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16.x
    - name: build blog
      shell: bash
      run: |
        npm ci
        npm run build
    - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          ACCESS_TOKEN: ${{ secrets.token }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: .vuepress/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      
    
      

